Repository kubeedge/mappers-go, pull requests merged in 2021-11, with the labels that each got.

#54 add e2e test
  Makefile
  go.mod
  go.sum
  hack/make-rules/device.sh
  hack/make-rules/e2e.sh
  tests/devices-simulator/modbus/Dockerfile
  tests/devices-simulator/modbus/Makefile
  tests/devices-simulator/modbus/cmd/main.go
  tests/devices-simulator/modbus/cmd/rtu/config/config.go
  tests/devices-simulator/modbus/cmd/rtu/rtu.go
  tests/devices-simulator/modbus/cmd/rtu/rtuerror.go
  tests/devices-simulator/modbus/cmd/tcp/config/config.go
  tests/devices-simulator/modbus/cmd/tcp/tcp.go
  tests/devices-simulator/modbus/cmd/tcp/tcperror.go
  tests/devices-simulator/modbus/device/convert.go
  tests/devices-simulator/modbus/device/run.go
  tests/devices-simulator/modbus/device/servererror.go
  tests/devices-simulator/modbus/device/thermometer.go
  tests/devices-simulator/modbus/hack/make-rules/device.sh
  tests/devices-simulator/opcua/Dockerfile
  tests/devices-simulator/opcua/device/cert.pem
  tests/devices-simulator/opcua/device/key.pem
  tests/devices-simulator/opcua/device/requirements.txt
  tests/devices-simulator/opcua/device/server.py
  tests/e2e/modbus/constants/constant.go
  tests/e2e/modbus/devicesprofiles/errorcode4.json
  tests/e2e/modbus/devicesprofiles/errortimeout.json
  tests/e2e/modbus/devicesprofiles/readholding.json
  tests/e2e/modbus/devicesprofiles/rtureadholding.json
  tests/e2e/modbus/devicesprofiles/writeint16.json
  tests/e2e/modbus/devicesprofiles/writeint32.json
  tests/e2e/modbus/hack/make-rules/e2e.sh
  tests/e2e/modbus/modbus_suite_test.go
  tests/e2e/modbus/modbus_test.go
  tests/e2e/opcua/ca/clientcert.pem
  tests/e2e/opcua/ca/clientkey.pem
  tests/e2e/opcua/ca/password.txt
  tests/e2e/opcua/ca/servercert.pem
  tests/e2e/opcua/ca/servercerterror.pem
  tests/e2e/opcua/constants/constant.go
  tests/e2e/opcua/devicesprofiles/certerror.json
  tests/e2e/opcua/devicesprofiles/opcuaDevice.json
  tests/e2e/opcua/devicesprofiles/opcuaDevice2.json
  tests/e2e/opcua/devicesprofiles/readfloat.json
  tests/e2e/opcua/devicesprofiles/writeint.json
  tests/e2e/opcua/hack/make-rules/e2e.sh
  tests/e2e/opcua/opcua_suite_test.go
  tests/e2e/opcua/opcua_test.go
  tests/e2e/utils/devices.go
  tests/e2e/utils/file.go
  tests/e2e/utils/logger.go
  tests/e2e/utils/mapper.go
Labels: lgtm, approved, size/XXL

#57 Remove useless []byte
  mappers/opcua/device/device.go
Labels: kind/feature, size/S, lgtm, approved

#55 fix spelling error and remove redundant code in ble module
  mappers/ble/config/config.go
  mappers/ble/configmap/type.go
  mappers/ble/device/device.go
  mappers/ble/device/twindata.go
  mappers/ble/globals/globals.go
Labels: kind/cleanup, size/S, lgtm, approved

#56 fix spelling error and remove redundant code in modbus module
  mappers/common/event.go
  mappers/modbus/config/config.go
  mappers/modbus/device/device.go
  mappers/modbus/driver/client.go
Labels: kind/cleanup, size/XS, lgtm, approved

#60 fix grammar error in onvif module
  mappers/onvif/config/config.go
  mappers/onvif/configmap/parse.go
  mappers/onvif/device/device.go
  mappers/onvif/device/event.go
  mappers/onvif/driver/img.go
Labels: kind/cleanup, size/S, lgtm, approved
