Repository kubeedge/mappers-go, pull requests merged in 2021-04, with the labels that each got.

#13 bluetooth mapper
  go.mod
  go.sum
  pkg/ble/Dockerfile
  pkg/ble/Makefile
  pkg/ble/config.go
  pkg/ble/config.yaml
  pkg/ble/config_test.go
  pkg/ble/configmap/configmap_test.json
  pkg/ble/configmap/parse.go
  pkg/ble/configmap/parse_test.go
  pkg/ble/configmap/type.go
  pkg/ble/deployment.yaml
  pkg/ble/device/device.go
  pkg/ble/device/devicestatus.go
  pkg/ble/device/twindata.go
  pkg/ble/driver/client.go
  pkg/ble/driver/const.go
  pkg/ble/globals/globals.go
  pkg/ble/main.go
Labels: approved, lgtm, size/XXL

#15 fix timer
  pkg/common/timer.go
Labels: approved, lgtm, size/S

#16 fix/global: use ble mapper replaces the old bluetooth mapper
  pkg/ble/configmap/parse.go
  pkg/ble/configmap/parse_test.go
  pkg/ble/configmap/type.go
  pkg/ble/device/device.go
  pkg/ble/device/devicestatus.go
  pkg/ble/device/twindata.go
  pkg/ble/driver/client.go
  pkg/ble/globals/globals.go
  pkg/bluetooth/Dockerfile
  pkg/bluetooth/OWNERS
  pkg/bluetooth/README.md
  pkg/bluetooth/action_manager/action_manager.go
  pkg/bluetooth/configuration/config.go
  pkg/bluetooth/configuration/config.yaml
  pkg/bluetooth/configuration/config_map_types.go
  pkg/bluetooth/controller/controller.go
  pkg/bluetooth/data_converter/data_converter.go
  pkg/bluetooth/deployment.yaml
  pkg/bluetooth/helper/helper.go
  pkg/bluetooth/main.go
  pkg/bluetooth/scheduler/scheduler.go
  pkg/bluetooth/watcher/watcher.go
Labels: approved, lgtm, size/XXL

#24 Move crd examples from kubeedge repo
  build/crd-samples/devices/CC2650-device-instance.yaml
  build/crd-samples/devices/CC2650-device-model.yaml
  build/crd-samples/devices/create-device-instance.yaml
  build/crd-samples/devices/create-device-model.yaml
  build/crd-samples/devices/led-light-device-instance.yaml
  build/crd-samples/devices/led-light-device-model.yaml
Labels: approved, lgtm, size/L

#22 Add ci for mappers-go
  .github/workflows/fossa.yml
  .github/workflows/main.yaml
  .golangci.yml
  Makefile
  hack/cherry_pick_pull.sh
  hack/lib/init.sh
  hack/lib/install.sh
  hack/lib/lint.sh
  hack/lib/util.sh
  hack/make-rules/bluetoothdevice.sh
  hack/make-rules/build.sh
  hack/make-rules/clean.sh
  hack/make-rules/crossbuild.sh
  hack/make-rules/lint.sh
  hack/make-rules/modbusmapper.sh
  hack/make-rules/smallbuild.sh
  hack/make-rules/test.sh
  hack/make-rules/version.sh
  hack/update-vendor-licenses.sh
  hack/update-vendor.sh
  hack/verify-golang.sh
  hack/verify-vendor-licenses.sh
  hack/verify-vendor.sh
  pkg/ble/configmap/parse.go
  pkg/ble/configmap/parse_test.go
  pkg/ble/device/device.go
  pkg/ble/device/devicestatus.go
  pkg/ble/device/twindata.go
  pkg/ble/driver/client.go
  pkg/ble/globals/globals.go
  pkg/ble/main.go
  pkg/modbus/configmap/parse.go
  pkg/modbus/configmap/parse_test.go
  pkg/modbus/device/device.go
  pkg/modbus/device/devstatus.go
  pkg/modbus/device/twindata.go
  pkg/modbus/main.go
  pkg/opcua/configmap/parse.go
  pkg/opcua/configmap/parse_test.go
  pkg/opcua/device/device.go
  pkg/opcua/device/devstatus.go
  pkg/opcua/driver/client.go
  pkg/opcua/driver/client_test.go
  pkg/opcua/main.go
  tests/e2e/mapper/bluetooth/bluetooth_test.go
Labels: approved, lgtm, size/XXL

#26 modify spelling errors
  pkg/ble/device/device.go
  pkg/ble/device/twindata.go
  pkg/modbus/configmap/type.go
  pkg/modbus/device/device.go
  pkg/modbus/driver/client.go
  pkg/opcua/device/device.go
Labels: approved, lgtm, size/S

#39 unify mqtt configuration to common
  pkg/ble/config.go
  pkg/common/event.go
  pkg/modbus/config.go
  pkg/modbus/device/device.go
  pkg/opcua/config.go
  pkg/opcua/main.go
Labels: approved, lgtm, size/M

#33 fix mapper process twin delta
  pkg/ble/device/device.go
  pkg/modbus/device/device.go
  pkg/opcua/device/device.go
Labels: approved, lgtm, size/XS
